---
- name: create user with shell and other inputs
  hosts: all
  become: yes
  vars: 
    greetings:
      - item1
      - item2
      - item3
  tasks:
    - name: create user with variables and multiple params
      debug:
        msg: "{{ greetings }}"
    - name: Create a group
      group:
        name: Check_group
        state: present
    - name: add multiple users
      user:
        name: "{{ item.name }}"
        shell: "{{ item.shell }}"
        group: "{{ item.group }}"
        uid: "{{ item.uid }}"
        description: "{{ item.description }}"
      loop: 
        - name: alice
          shell: /bin/sh
          group: Check_group
          uid: 1040
          description: "alice description"
        - name: bob
          shell: /bin/sh
          group: Check_group
          uid: 1041
          description: "bob description"