---
- name: To install httpd and ensure apache is running
  hosts: group
  become: yes
  vars:        # variables used for create multiple users job
    users_to_create:
      - name: alice
        password: "{{ 'password123' | password_hash('sha512', 'mysecretsalt') }}"
        groups: Multipleusers
      - name: bob
        password: "{{ 'password456' | password_hash('sha512', 'mysecretsalt') }}"
        groups: Multipleusers
  tasks:
    # create multiple users with items 
    - name: Create multiple users
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        groups: "{{ item.groups }}"
        state: present
      with_items: "{{ users_to_create }}"     # will execute the variables one by one mentioned in var
    



