---
- name: To install httpd and ensure apache is running
  hosts: group
  become: yes
  tasks:
    - name: Installation of httpd
      yum:
        name: httpd
        state: latest

    - name: Ensure apache is running
      service:
        name: httpd
        state: started

    - name: Copy file to a remote machine
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
        force: yes

    - name: Change the listening port to 81
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 80'
        insertafter: '^#Listen '
        line: Listen 81   

    - name: ensure apache is running
      service:
        name: httpd
        state: restarted

    - name: execute the curl command
      shell:
         cmd: curl localhost:81 > /tmp/output.txt

    # create multiple users with items 
    - name: Create multiple users
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        groups: "{{ item.groups }}"
        state: present
      with_items: "{{ users_to_create }}"
    
    # variables used for create multiple users job
  vars:
    users_to_create:
      - name: alice
        password: "{{ 'password123' | password_hash('sha512', 'mysecretsalt') }}"
        groups: Multipleusers
      - name: bob
        password: "{{ 'password456' | password_hash('sha512', 'mysecretsalt') }}"
        groups: Multipleusers


