---
- name: using varibales
  hosts: all
  become: yes
  vars:
    names:
      - kaith
      - lohitha
      - vinothini
    dictionary:
      project: "tesco"
      company: "nagarro"
    
  tasks: 
    - name: printing the value from varibales
      debug:
        msg: "printing the variable from array {{ names[1]}}"
        msg: "printing the variable from dictionary {{ dictionary }}"