---
- name: to check block
  hosts: all
  tasks:
    - name: Install, configure, and start Apache
      block:
        - name: Print Hostname
          debug:
            var: ansible_facts
        - name: Install httpd and mlocate
          yum:
            name:
              - httpd
              - mlocate
            state: present
        - name: checking ignore error
          shell:
            cmd: 2nd task executed

        - name: Start service bar and enable it
          debug:
            msg: "2nd task executed"
      when: ansible_facts["ansible_user_shell"] == "/bin/bash"
      become: true
      become_user: root
      ignore_errors: true