---
- name: block and rescue
  hosts: all
  become: yes
  tasks:
    - name: check block and rescue
      block:
        - name: this task will fail
          shell:
            cmd: this command will fail
      rescue: 
        - name: this rescue will run
          debug:
            msg: "rescue job run"

      block:
        - name: this task will fail
          shell:
            cmd: ls
      rescue:
        - name: this rescue will not run
          debug:
            msg: "rescue will not run"