---
- name: check notify and handlers
  hosts: all
  tasks:
    - name: to run a sample ls command
      shell:
        cmd: ls
      notify: display a message
    - name: to run a sample date command
      shell:
        cmd: date
      notify: display a message
  handlers:
    - name: display a message
      debug:
        msg: "this is a sample message after task"