---
- name: To install httpd and ensure apache is running
  hosts: group
  become: yes
  tasks:
    # gather facts
    - name: Print all
      debug:
        var: ansible_facts

    - name: Print Hostname
      debug:
        var: ansible_hostname  # magic variables

    # using gather facts
    - name: Install httpd on RedHat-based systems
      package:
        name: "httpd"
        state: present
      when: ansible_user_shell == "/bin/bash"

    - name: Install apache2 on Ubuntu-based systems
      package:
        name: "apache2"
        state: present
      when: ansible_user_shell == "/bin/zsh"
      # check



