---
# tasks file for samplerole
- name: check the ordinary var
  debug:
    msg: "ordinary_var: {{sample_var}}"

- name: check the default var
  debug:
    msg: "default_var: {{default_var}}"

- name: run ls sample task
  shell:
    cmd: ls
  notify: "run_after_check"

- name: run date sample task
  shell:
    cmd: date
  notify: "run_after_check"