---
- name: practice templates
  hosts: all
  tasks:
    - name: create a .conf file for tomcat
      template:
        src: /home/ansible_user/SamplePlaybooks/template-examples/template/conf.j2
        dest: /tmp/sample/tomcat/config.conf
      vars: 
        port_number: 80
    - name: create a .conf file for httpd
      template:
        src: /home/ansible_user/SamplePlaybooks/template-examples/template/conf.j2
        dest: /tmp/sample/apache/config.conf
      vars: 
        port_number: 81


# ansible-playbook template-examples/sample-template.yaml -i hostfile
