---
- name: check the vault reading
  hosts: all
  tasks:
    - name: Include the vault file
      include_vars: /home/ansible_user/SamplePlaybooks/my_vault.yaml
    - name: check the variable reading from vault
      debug: 
        var: my_secret